import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Compass, Globe2, MoveUpRight } from "lucide-react";
import Shell from "@/components/Shell";
import Stats from "@/components/Stats";
import SectionHeader from "@/components/SectionHeader";
import AircraftCard from "@/components/AircraftCard";
import DestinationCard from "@/components/DestinationCard";
import FlightTracker from "@/components/FlightTracker";
import DiscordSection from "@/components/DiscordSection";
import { site } from "@/data/site";
import { aircraft } from "@/data/aircraft";
import { destinations } from "@/data/destinations";

export default function Home() { return <Shell><main>
  <section className="relative min-h-[760px] overflow-hidden pt-[76px]"><Image src={site.heroImage} alt="Commercial aircraft above a sea of clouds" fill priority sizes="100vw" className="object-cover object-center" /><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(6,17,31,.93)_0%,rgba(6,17,31,.55)_48%,rgba(6,17,31,.2)_100%)]" /><div className="absolute inset-0 bg-[linear-gradient(0deg,#06111f_0%,transparent_35%)]" /><div className="relative mx-auto flex min-h-[684px] max-w-[1200px] items-center px-5 lg:px-8"><div className="max-w-2xl reveal"><p className="eyebrow mb-6">Osaka, Japan · Low-cost carrier · Est. 17 September 2026</p><h1 className="display-font text-7xl leading-[.84] md:text-[9rem]">AER<br /><span className="text-[#54d5ff]">INFINITY</span></h1><p className="mt-8 max-w-lg text-lg leading-8 text-[#d1deeb]">A Kansai-based airline development experiment, growing from a focused domestic network into an international carrier one route at a time.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/about" className="flex items-center gap-3 bg-[#f4f8fc] px-5 py-3 text-xs font-bold uppercase tracking-widest text-[#06111f] transition hover:bg-[#54d5ff]">Discover Aer Infinity <ArrowRight size={15} /></Link><Link href="/destinations" className="border border-white/40 px-5 py-3 text-xs font-bold uppercase tracking-widest text-white transition hover:border-[#54d5ff] hover:text-[#54d5ff]">Explore routes</Link></div></div></div><div className="absolute bottom-7 left-1/2 w-[calc(100%-2.5rem)] max-w-[1160px] -translate-x-1/2 border border-white/15 bg-[#06111f]/60 p-4 backdrop-blur-xl"><div className="grid grid-cols-3 gap-3 text-[10px] font-bold uppercase tracking-[.18em] text-[#8fa5bc]"><div><span className="block text-[#54d5ff]">From</span>Kansai · KIX</div><div><span className="block text-[#54d5ff]">To</span>Japan</div><div><span className="block text-[#54d5ff]">Next phase</span>International</div></div></div></section>
  <section className="section-pad pb-20"><Stats /></section>
  <section className="section-pad grid items-center gap-12 pt-0 lg:grid-cols-[.9fr_1.1fr]"><div><SectionHeader eyebrow="01 / The airline" title="Small beginnings. A bigger horizon." text="Founded in Osaka on 17 September 2026 by R3XI, Aer Infinity is a low-cost airline development experiment based at Kansai International Airport. The plan is deliberate growth: establish the operation, build the network, and expand internationally as the airline develops." /><Link href="/about" className="inline-flex items-center gap-2 text-xs font-bold uppercase tracking-widest text-[#54d5ff]">Read our story <MoveUpRight size={15} /></Link></div><div className="relative aspect-[1.2] overflow-hidden border border-white/10"><Image src="https://images.unsplash.com/photo-1436491865332-7a61a109cc05?auto=format&fit=crop&w=1400&q=80" alt="Airliner wing above cloud cover" fill sizes="(max-width: 1024px) 100vw, 50vw" className="object-cover" /><div className="absolute bottom-4 left-4 glass px-4 py-3 text-[10px] font-bold uppercase tracking-widest"><span className="text-[#54d5ff]">KIX / RJBB</span><br />Primary hub · Osaka</div></div></section>
  <section className="section-pad grid-bg"><SectionHeader eyebrow="02 / The fleet" title="One type. A clear beginning." text="Aer Infinity began with the Airbus A320-200, a focused fleet platform for building domestic and regional operations from Kansai." /><div className="grid gap-5 md:grid-cols-3">{aircraft.slice(0, 3).map((item) => <AircraftCard key={item.slug} item={item} />)}</div><Link href="/fleet" className="mt-8 inline-flex items-center gap-2 text-xs font-bold uppercase tracking-widest text-[#54d5ff]">View fleet details <ArrowRight size={15} /></Link></section>
  <section className="section-pad"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><SectionHeader eyebrow="03 / Network" title="Japan, from Kansai." text="The initial network connects Osaka with Tokyo, Fukuoka, and Sapporo. International routes are planned for the next stage of development." /><Link href="/destinations" className="mb-12 inline-flex items-center gap-2 text-xs font-bold uppercase tracking-widest text-[#54d5ff]">Explore network <Globe2 size={15} /></Link></div><div className="grid gap-5 md:grid-cols-3">{destinations.slice(0, 3).map((item) => <DestinationCard key={item.code} item={item} />)}</div></section>
  <section className="section-pad border-y border-white/10 bg-[#081829]"><div className="mb-8 flex items-end justify-between"><div><p className="eyebrow mb-3">Live / virtual operations</p><h2 className="display-font text-4xl">In the air, together.</h2></div><Compass className="hidden text-[#54d5ff] md:block" size={38} /></div><FlightTracker /></section>
  <DiscordSection />
</main></Shell>; }
